version: "3.9"
services:
  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  # Admin API Service
  admin_api:
      build: ./admin_api
      container_name: adminservice
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./admin_api:/app/admin_api
      ports:
        - "8000:8000"
      depends_on:
        - rabbitmq
  
  # Client API Service
  client_api:
      build: ./client_api
      container_name: clientservice
      command: python manage.py runserver 0.0.0.0:8008
      volumes:
        - ./client_api:/app/client_api
      ports:
        - "8008:8008"
      depends_on:
        - rabbitmq
    
  # Celery Worker for Client API
  celery_worker_client:
    restart: always
    build: 
      context: ./client_api # Build from the client_api project
    command: celery -A client_api worker -l info 
    volumes: 
      - .:/app
    container_name: celery_client
    depends_on:
      - rabbitmq
      - client_api

  # Celery Worker for Admin API
  celery_worker_admin:
    restart: always
    build: 
      context: ./admin_api # Build from the admin_api project
    command: celery -A admin_api worker -l info 
    volumes: 
      - .:/app
    container_name: celery_admin
    depends_on:
      - rabbitmq
      - admin_api
    