version: "3.9"
services:
  admin_api:
      build: ./admin-api
      container_name: adminservice
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./admin-api:/app/admin-api
      ports:
        - "8000:8000"
      # networks:
      #   - isolation-network
  client_api:
      build: ./client-api
      container_name: clientservice
      command: python manage.py runserver 0.0.0.0:8080
      volumes:
        - ./client-api:/app/client-api
      ports:
        - "8080:8080"
      depends_on:
        - admin_api
      # networks:
      #   - isolation-network
      
    