version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  admin_api:
      build: ./admin-api
      container_name: adminservice
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./admin-api:/app/admin-api
      ports:
        - "8000:8000"
  client_api:
      build: ./client-api
      container_name: clientservice
      command: python manage.py runserver 0.0.0.0:8008
      volumes:
        - ./client-api:/app/client-api
      ports:
        - "8008:8008"
  celery:
    restart: always
    build: 
      context: ./client-api # Build from the client_api project
    command: celery -A client_api worker -l info 
    volumes: 
      - .:/app
    container_name: library_celery
    depends_on:
      - rabbitmq
      - admin_api
      - client_api
    environment:
      - CELERY_IMPORTS=admin_api.tasks,client_api.tasks

      
    