# Generated by Django 3.2.12 on 2023-08-07 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookloaned_date_borrowed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year_published',
        ),
        migrations.RemoveField(
            model_name='bookloaned',
            name='duration',
        ),
        migrations.AddField(
            model_name='bookloaned',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookloaned',
            name='date_borrowed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
