# Generated by Django 3.2.12 on 2023-08-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230807_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookLoaned',
            new_name='LoanedBook',
        ),
    ]
