# Generated by Django 3.2.12 on 2022-02-10 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='bookloaned',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bookloaned',
            name='date_borrowed',
            field=models.DateField(default=datetime.datetime(2022, 2, 10, 18, 58, 45, 116163)),
        ),
    ]
